---
output: bookdown::html_document2
bibliography: bibfile.bib
fig_caption: yes
header-includes:
- \usepackage{float}
- \floatsetup[table]{capposition=bot}
---

# Classificação

Algoritmos de classificação são aqueles [...]

<!-- Somente três serão apresentados -->
<!-- Acho que isso aqui pode ser substituído por uma figura e então, comentários em cima dela podem ser feitos-->
Classes de algoritmos: (Modelos probabilisticos; Decision Trees; *Instance-based Learning*)

***Instance-basedLearning***

<!-- Rascunho -->
Na aprendizagem baseada em exemplos, a primeira fase da construção do modelo de treinamento é freqüentemente dispensada. A instância de teste está diretamente relacionada com as instâncias de treinamento a fim de criar um modelo de classificação. Tais métodos são chamados de métodos de aprendizagem preguiçosos, pois aguardam o conhecimento da instância de teste para criar um modelo otimizado localmente, que é específico para a instância de teste. A vantagem de tais métodos é que eles podem ser adaptados diretamente à instância de teste específica, e podem evitar a perda de informação associada à incompletude de qualquer modelo de treinamento.

## Exemplos de algoritmos de classificação

### Naive Bayes

### $k$-Nearest Neighbors

*Somos a **soma** dos que nos cercam*

<!-- Rascunho do texto base para a apresentação do kNN-->

<!-- Conceitos gerais -->
$k$-Nearest Neighbors (kNN) é um algoritmo de classificação supervisionado que através da assimilação de elementos já classificados define a classe a qual um determinado elemento vai pertencer.

- Este é um algoritmo que é criado utilizando a ideia base de que os dados que representam fenômenos relacionados e por conta disso, compartilham características.

- Distâncias
  - Euclidean;
  - Mahalanobis

- Complexidade

<!-- ToDo: Adicionar três figuras nessa parte: (i) Pouca quantidade de pontos; (ii) Quantidade média de pontos; (iii) Grande quantidade de pontos -->
<!-- Isso ajuda a pessoa a entender a escala de crescimento da complexidade -->

<!-- Escolha do K -->



<!-- Visualização do funcionamento -->

<!-- Exemplos de uso  -->

### Decision Tree
